// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (id, class_id, created_at, updated_at, due_at, title, instructions, allow_late)
VALUES (
        gen_random_uuid(),
        $1,
        NOW(),
        NOW(),
        $2,
        $3,
        $4,
        $5
)
RETURNING id, class_id, created_at, updated_at, due_at, title, instructions, allow_late
`

type CreateAssignmentParams struct {
	ClassID      uuid.UUID
	DueAt        sql.NullTime
	Title        string
	Instructions sql.NullString
	AllowLate    bool
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignment,
		arg.ClassID,
		arg.DueAt,
		arg.Title,
		arg.Instructions,
		arg.AllowLate,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAt,
		&i.Title,
		&i.Instructions,
		&i.AllowLate,
	)
	return i, err
}
