// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (id, class_id, created_at, updated_at, due_at, title, instructions, allow_late)
VALUES (
        gen_random_uuid(),
        $1,
        NOW(),
        NOW(),
        $2,
        $3,
        $4,
        $5
)
RETURNING id, class_id, created_at, updated_at, due_at, title, instructions, allow_late
`

type CreateAssignmentParams struct {
	ClassID      uuid.UUID
	DueAt        sql.NullTime
	Title        string
	Instructions sql.NullString
	AllowLate    bool
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignment,
		arg.ClassID,
		arg.DueAt,
		arg.Title,
		arg.Instructions,
		arg.AllowLate,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAt,
		&i.Title,
		&i.Instructions,
		&i.AllowLate,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :one
DELETE FROM assignments
WHERE id = $1
RETURNING id, class_id, created_at, updated_at, due_at, title, instructions, allow_late
`

func (q *Queries) DeleteAssignment(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, deleteAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAt,
		&i.Title,
		&i.Instructions,
		&i.AllowLate,
	)
	return i, err
}

const getAssignmentFromID = `-- name: GetAssignmentFromID :one
SELECT id, class_id, created_at, updated_at, due_at, title, instructions, allow_late FROM assignments
WHERE id = $1
`

func (q *Queries) GetAssignmentFromID(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentFromID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueAt,
		&i.Title,
		&i.Instructions,
		&i.AllowLate,
	)
	return i, err
}

const getAssignmentsForAClass = `-- name: GetAssignmentsForAClass :many
SELECT id, class_id, created_at, updated_at, due_at, title, instructions, allow_late FROM assignments
WHERE class_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAssignmentsForAClass(ctx context.Context, classID uuid.UUID) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsForAClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueAt,
			&i.Title,
			&i.Instructions,
			&i.AllowLate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNumAssignmentsToDo = `-- name: GetNumAssignmentsToDo :one
SELECT COUNT(assignments.title) FROM students_classes
INNER JOIN classes ON classes.id = students_classes.class_id
INNER JOIN assignments ON assignments.class_id = classes.id
WHERE students_classes.student_id = $1
AND NOW() < assignments.due_at
`

func (q *Queries) GetNumAssignmentsToDo(ctx context.Context, studentID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumAssignmentsToDo, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
