// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (id, created_at, updated_at, name, teacher_id, allow_joining)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        true
)
RETURNING id, created_at, updated_at, name, teacher_id, allow_joining
`

type CreateClassParams struct {
	Name      string
	TeacherID uuid.UUID
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Name, arg.TeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeacherID,
		&i.AllowJoining,
	)
	return i, err
}

const getClass = `-- name: GetClass :one
SELECT classes.id, classes.created_at, classes.updated_at,
        classes.name, classes.teacher_id, classes.allow_joining, users.name as teacher_name
FROM classes
INNER JOIN users
        ON classes.teacher_id = users.id
WHERE classes.id = $1
`

type GetClassRow struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	TeacherID    uuid.UUID
	AllowJoining bool
	TeacherName  string
}

func (q *Queries) GetClass(ctx context.Context, id uuid.UUID) (GetClassRow, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i GetClassRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeacherID,
		&i.AllowJoining,
		&i.TeacherName,
	)
	return i, err
}

const getClassFromClassID = `-- name: GetClassFromClassID :one
SELECT id, created_at, updated_at, name, teacher_id, allow_joining FROM classes
WHERE id = $1
`

func (q *Queries) GetClassFromClassID(ctx context.Context, id uuid.UUID) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClassFromClassID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeacherID,
		&i.AllowJoining,
	)
	return i, err
}

const getClassesAsStudent = `-- name: GetClassesAsStudent :many
SELECT id, created_at, updated_at, name, teacher_id, allow_joining FROM classes
WHERE id IN (
        SELECT class_id
        FROM students_classes
        WHERE student_id = $1
)
`

func (q *Queries) GetClassesAsStudent(ctx context.Context, studentID uuid.UUID) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, getClassesAsStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.TeacherID,
			&i.AllowJoining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassesAsTeacher = `-- name: GetClassesAsTeacher :many
SELECT id, created_at, updated_at, name, teacher_id, allow_joining FROM classes
WHERE teacher_id = $1
`

func (q *Queries) GetClassesAsTeacher(ctx context.Context, teacherID uuid.UUID) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, getClassesAsTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.TeacherID,
			&i.AllowJoining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinClass = `-- name: JoinClass :one
INSERT INTO students_classes (id, joined_at, updated_at, student_id, class_id)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2
)
RETURNING id, joined_at, updated_at, student_id, class_id
`

type JoinClassParams struct {
	StudentID uuid.UUID
	ClassID   uuid.UUID
}

func (q *Queries) JoinClass(ctx context.Context, arg JoinClassParams) (StudentsClass, error) {
	row := q.db.QueryRowContext(ctx, joinClass, arg.StudentID, arg.ClassID)
	var i StudentsClass
	err := row.Scan(
		&i.ID,
		&i.JoinedAt,
		&i.UpdatedAt,
		&i.StudentID,
		&i.ClassID,
	)
	return i, err
}

const removeUserFromClass = `-- name: RemoveUserFromClass :exec
DELETE FROM students_classes
WHERE student_id = $1 AND class_id = $2
`

type RemoveUserFromClassParams struct {
	StudentID uuid.UUID
	ClassID   uuid.UUID
}

func (q *Queries) RemoveUserFromClass(ctx context.Context, arg RemoveUserFromClassParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromClass, arg.StudentID, arg.ClassID)
	return err
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes
SET
        name = $2,
        teacher_id = $3,
        allow_joining = $4,
        updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, teacher_id, allow_joining
`

type UpdateClassParams struct {
	ID           uuid.UUID
	Name         string
	TeacherID    uuid.UUID
	AllowJoining bool
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, updateClass,
		arg.ID,
		arg.Name,
		arg.TeacherID,
		arg.AllowJoining,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeacherID,
		&i.AllowJoining,
	)
	return i, err
}
