// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (id, created_at, updated_at, name, teacher_id)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2
)
RETURNING id, created_at, updated_at, name, teacher_id
`

type CreateClassParams struct {
	Name      string
	TeacherID uuid.UUID
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Name, arg.TeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeacherID,
	)
	return i, err
}
