// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: class_content.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createClassContent = `-- name: CreateClassContent :one
INSERT INTO class_content (id, created_at, updated_at, content_type, class_id, title, content)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        $3,
        $4
)
RETURNING id, created_at, updated_at, content_type, class_id, title, content
`

type CreateClassContentParams struct {
	ContentType string
	ClassID     uuid.UUID
	Title       string
	Content     sql.NullString
}

func (q *Queries) CreateClassContent(ctx context.Context, arg CreateClassContentParams) (ClassContent, error) {
	row := q.db.QueryRowContext(ctx, createClassContent,
		arg.ContentType,
		arg.ClassID,
		arg.Title,
		arg.Content,
	)
	var i ClassContent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentType,
		&i.ClassID,
		&i.Title,
		&i.Content,
	)
	return i, err
}

const getClassContent = `-- name: GetClassContent :one
SELECT id, created_at, updated_at, content_type, class_id, title, content FROM class_content
WHERE id = $1
`

func (q *Queries) GetClassContent(ctx context.Context, id uuid.UUID) (ClassContent, error) {
	row := q.db.QueryRowContext(ctx, getClassContent, id)
	var i ClassContent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentType,
		&i.ClassID,
		&i.Title,
		&i.Content,
	)
	return i, err
}

const getClassContentForClass = `-- name: GetClassContentForClass :many
SELECT id, title, created_at FROM class_content
WHERE class_id = $2 AND content_type = $1
ORDER BY created_at DESC
`

type GetClassContentForClassParams struct {
	ContentType string
	ClassID     uuid.UUID
}

type GetClassContentForClassRow struct {
	ID        uuid.UUID
	Title     string
	CreatedAt time.Time
}

func (q *Queries) GetClassContentForClass(ctx context.Context, arg GetClassContentForClassParams) ([]GetClassContentForClassRow, error) {
	rows, err := q.db.QueryContext(ctx, getClassContentForClass, arg.ContentType, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassContentForClassRow
	for rows.Next() {
		var i GetClassContentForClassRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassContent = `-- name: UpdateClassContent :one
UPDATE class_content
SET
        title = $2,
        content = $3,
        updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, content_type, class_id, title, content
`

type UpdateClassContentParams struct {
	ID      uuid.UUID
	Title   string
	Content sql.NullString
}

func (q *Queries) UpdateClassContent(ctx context.Context, arg UpdateClassContentParams) (ClassContent, error) {
	row := q.db.QueryRowContext(ctx, updateClassContent, arg.ID, arg.Title, arg.Content)
	var i ClassContent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentType,
		&i.ClassID,
		&i.Title,
		&i.Content,
	)
	return i, err
}
