// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (id, created_at, updated_at, name, teacher_id)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2
)
RETURNING id, created_at, updated_at, name, teacher_id
`

type CreateClassParams struct {
	Name      string
	TeacherID uuid.UUID
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Name, arg.TeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TeacherID,
	)
	return i, err
}

const getClassesAsStudent = `-- name: GetClassesAsStudent :many
SELECT id, created_at, updated_at, name, teacher_id FROM classes
WHERE id IN (
        SELECT class_id
        FROM students_classes
        WHERE student_id = $1
)
`

func (q *Queries) GetClassesAsStudent(ctx context.Context, studentID uuid.UUID) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, getClassesAsStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.TeacherID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassesAsTeacher = `-- name: GetClassesAsTeacher :many
SELECT id, created_at, updated_at, name, teacher_id FROM classes
WHERE teacher_id = $1
`

func (q *Queries) GetClassesAsTeacher(ctx context.Context, teacherID uuid.UUID) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, getClassesAsTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.TeacherID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentsForClass = `-- name: GetStudentsForClass :many
SELECT id,name FROM users
WHERE id IN (
        SELECT student_id
        FROM students_classes
        WHERE class_id = $1
)
`

type GetStudentsForClassRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetStudentsForClass(ctx context.Context, classID uuid.UUID) ([]GetStudentsForClassRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentsForClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentsForClassRow
	for rows.Next() {
		var i GetStudentsForClassRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinClass = `-- name: JoinClass :one
INSERT INTO students_classes (id, joined_at, updated_at, student_id, class_id)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2
)
RETURNING id, joined_at, updated_at, student_id, class_id
`

type JoinClassParams struct {
	StudentID uuid.UUID
	ClassID   uuid.UUID
}

func (q *Queries) JoinClass(ctx context.Context, arg JoinClassParams) (StudentsClass, error) {
	row := q.db.QueryRowContext(ctx, joinClass, arg.StudentID, arg.ClassID)
	var i StudentsClass
	err := row.Scan(
		&i.ID,
		&i.JoinedAt,
		&i.UpdatedAt,
		&i.StudentID,
		&i.ClassID,
	)
	return i, err
}
