// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Assignment struct {
	ID           uuid.UUID
	ClassID      uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DueAt        sql.NullTime
	Title        string
	Instructions sql.NullString
	AllowLate    sql.NullBool
}

type Class struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	TeacherID uuid.UUID
}

type StudentsClass struct {
	ID        uuid.UUID
	JoinedAt  time.Time
	UpdatedAt time.Time
	StudentID uuid.UUID
	ClassID   uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	HashedPassword string
}
