// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (id, created_at, updated_at, class_id, title, content)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        $3
)
RETURNING id, created_at, updated_at, class_id, title, content
`

type CreateResourceParams struct {
	ClassID uuid.UUID
	Title   string
	Content sql.NullString
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource, arg.ClassID, arg.Title, arg.Content)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClassID,
		&i.Title,
		&i.Content,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT id, created_at, updated_at, class_id, title, content FROM resources
WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id uuid.UUID) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClassID,
		&i.Title,
		&i.Content,
	)
	return i, err
}

const getResourcesForClass = `-- name: GetResourcesForClass :many
SELECT id, title, created_at FROM resources
WHERE class_id = $1
ORDER BY created_at DESC
`

type GetResourcesForClassRow struct {
	ID        uuid.UUID
	Title     string
	CreatedAt time.Time
}

func (q *Queries) GetResourcesForClass(ctx context.Context, classID uuid.UUID) ([]GetResourcesForClassRow, error) {
	rows, err := q.db.QueryContext(ctx, getResourcesForClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesForClassRow
	for rows.Next() {
		var i GetResourcesForClassRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
        title = $2,
        content = $3,
        updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, class_id, title, content
`

type UpdateResourceParams struct {
	ID      uuid.UUID
	Title   string
	Content sql.NullString
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource, arg.ID, arg.Title, arg.Content)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClassID,
		&i.Title,
		&i.Content,
	)
	return i, err
}
