// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (id, created_at, updated_at, assignment_id, user_id, answers)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        $3
)
RETURNING id, created_at, updated_at, assignment_id, user_id, answers, score
`

type CreateSubmissionParams struct {
	AssignmentID uuid.UUID
	UserID       uuid.UUID
	Answers      sql.NullString
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission, arg.AssignmentID, arg.UserID, arg.Answers)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.UserID,
		&i.Answers,
		&i.Score,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, created_at, updated_at, assignment_id, user_id, answers, score FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.UserID,
		&i.Answers,
		&i.Score,
	)
	return i, err
}

const getSubmissionForUser = `-- name: GetSubmissionForUser :one
SELECT id, created_at, updated_at, assignment_id, user_id, answers, score FROM submissions
WHERE assignment_id = $1 AND user_id = $2
`

type GetSubmissionForUserParams struct {
	AssignmentID uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) GetSubmissionForUser(ctx context.Context, arg GetSubmissionForUserParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionForUser, arg.AssignmentID, arg.UserID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.UserID,
		&i.Answers,
		&i.Score,
	)
	return i, err
}

const getSubmissionsForAssignment = `-- name: GetSubmissionsForAssignment :many
SELECT submissions.id, submissions.created_at, submissions.updated_at,
        submissions.user_id, submissions.answers, users.name
FROM submissions
INNER JOIN users
        ON submissions.user_id = users.id
WHERE assignment_id = $1
`

type GetSubmissionsForAssignmentRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	Answers   sql.NullString
	Name      string
}

func (q *Queries) GetSubmissionsForAssignment(ctx context.Context, assignmentID uuid.UUID) ([]GetSubmissionsForAssignmentRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubmissionsForAssignment, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionsForAssignmentRow
	for rows.Next() {
		var i GetSubmissionsForAssignmentRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Answers,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gradeSubmission = `-- name: GradeSubmission :one
UPDATE submissions
SET
        score = $2,
        updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, assignment_id, user_id, answers, score
`

type GradeSubmissionParams struct {
	ID    uuid.UUID
	Score sql.NullInt32
}

func (q *Queries) GradeSubmission(ctx context.Context, arg GradeSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, gradeSubmission, arg.ID, arg.Score)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.UserID,
		&i.Answers,
		&i.Score,
	)
	return i, err
}

const updateSubmission = `-- name: UpdateSubmission :one
UPDATE submissions
SET
        answers = $2,
        updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, assignment_id, user_id, answers, score
`

type UpdateSubmissionParams struct {
	ID      uuid.UUID
	Answers sql.NullString
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, updateSubmission, arg.ID, arg.Answers)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.UserID,
		&i.Answers,
		&i.Score,
	)
	return i, err
}
