// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (id, created_at, updated_at, assignment_id, user_id, answers)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        $3
)
RETURNING id, created_at, updated_at, assignment_id, user_id, answers
`

type CreateSubmissionParams struct {
	AssignmentID uuid.UUID
	UserID       uuid.UUID
	Answers      sql.NullString
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission, arg.AssignmentID, arg.UserID, arg.Answers)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignmentID,
		&i.UserID,
		&i.Answers,
	)
	return i, err
}
