// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, email, hashed_password)
VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        $3
)
RETURNING id, created_at, updated_at, name, email, hashed_password, bio
`

type CreateUserParams struct {
	Name           string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getStudentsForClass = `-- name: GetStudentsForClass :many
SELECT id,name,created_at FROM users
WHERE id IN (
        SELECT student_id
        FROM students_classes
        WHERE class_id = $1
)
ORDER BY name
`

type GetStudentsForClassRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) GetStudentsForClass(ctx context.Context, classID uuid.UUID) ([]GetStudentsForClassRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentsForClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentsForClassRow
	for rows.Next() {
		var i GetStudentsForClassRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalUserCount = `-- name: GetTotalUserCount :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetTotalUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserFromEmail = `-- name: GetUserFromEmail :one
SELECT id, created_at, updated_at, name, email, hashed_password, bio FROM users
WHERE email = $1
`

func (q *Queries) GetUserFromEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
	)
	return i, err
}

const getUserFromID = `-- name: GetUserFromID :one
SELECT id, created_at, updated_at, name, email, hashed_password, bio FROM users
WHERE id = $1
`

func (q *Queries) GetUserFromID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
	)
	return i, err
}

const updateUserImportant = `-- name: UpdateUserImportant :one
UPDATE users
SET
        email = $2,
        hashed_password = $3,
        updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, email, hashed_password, bio
`

type UpdateUserImportantParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUserImportant(ctx context.Context, arg UpdateUserImportantParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserImportant, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
	)
	return i, err
}

const updateUserLessImportant = `-- name: UpdateUserLessImportant :one
UPDATE users
SET
        name = $2,
        bio = $3,
        updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, email, hashed_password, bio
`

type UpdateUserLessImportantParams struct {
	ID   uuid.UUID
	Name string
	Bio  string
}

func (q *Queries) UpdateUserLessImportant(ctx context.Context, arg UpdateUserLessImportantParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserLessImportant, arg.ID, arg.Name, arg.Bio)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
	)
	return i, err
}
